services:
  app:
    image: todo-front-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    container_name: todo-front-dev # This will name the container hello-front-dev
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:4000/
      NODE_OPTIONS: --openssl-legacy-provider
